#!/usr/bin/python3

from os import system
from os import execvp

system('/scripts/set_system_timezone.py')
system('/scripts/setup_samba.py')
execvp('supervisord', ['supervisord', '--configuration', '/etc/supervisord.conf'])
